use crate::error::Exception;

pub trait EventPublisher {
    fn publish_tracking_event(screen: String, action: String, category: String, label: String);
    fn publish_undo_evnet(can_undo: bool, can_redo: bool);
    fn publish_redo_event(can_redo: bool, can_undo: bool);
    // TODO
    fn publish_push_undo_command_event();
    fn publish_add_model_event();
    fn publish_set_active_model_event();
    fn publish_set_active_bone_event();
    fn publish_set_active_morph_event();
    fn publish_remove_model_event();
    fn publish_add_accessory_event();
    fn publish_set_active_accessory_event();
    fn publish_remove_accessory_event();
    fn publish_add_motion_event();
    fn publish_remove_motion_event();
    fn publish_play_event();
    fn publish_pause_event();
    fn publish_resume_event();
    fn publish_stop_event();
    fn publish_seek_event();
    fn publish_update_duration_event();
    fn publish_toggle_project_effect_enabled_event(value: bool);
    fn publish_toggle_project_ground_shadow_enabled_event(value: bool);
    fn publish_toggle_project_vertex_shader_skinning_enabled_event(value: bool);
    fn publish_toggle_project_compute_shader_skinning_enabled_event(value: bool);
    fn publish_set_project_sample_level_event(value: u32);
    fn publish_toggle_grid_enabled_event(value: bool);
    fn publish_set_grid_cell_event();
    fn publish_set_grid_size_event();
    fn publish_set_preferred_motion_fps_event(value: u32, unlimited: bool);
    fn publish_set_preferred_editing_fps_event(value: u32);
    fn publish_set_physics_simulation_mode_event(value: u32);
    fn publish_set_physics_simulation_engine_debug_flag_event(value: u32);
    fn publish_toggle_shadow_map_enabled_event(value: bool);
    fn publish_set_shadow_map_mode_event(value: u32);
    fn publish_set_shadow_map_distance_event(value: u32);
    fn publish_toggle_active_model_add_blend_enabled_event(value: bool);
    fn publish_toggle_active_model_shadow_map_enabled_event(value: bool);
    fn publish_toggle_active_model_visible_event(value: bool);
    fn publish_toggle_active_model_compute_shader_skinning_enabled_event(value: bool);
    fn publish_toggle_active_model_show_all_bones_event(value: bool);
    fn publish_toggle_active_model_show_all_rigid_bodies_event(value: bool);
    fn publish_toggle_active_model_show_all_vertex_faces_event(value: bool);
    fn publish_toggle_active_model_show_all_vertex_points_event(value: bool);
    fn publish_toggle_active_model_vertex_shader_skinning_enabled_event(value: bool);
    fn publish_toggle_project_playing_with_loop_enabled_event(value: bool);
    fn publish_toggle_active_accessary_add_blend_enabled_event(value: bool);
    fn publish_toggle_active_accessary_ground_shadow_enabled_event(value: bool);
    fn publish_toggle_active_accessary_visible_event(value: bool);
    fn publish_toggle_model_editing_enabled_event(value: bool);
    fn publish_consume_pass_event(value: u32);
    fn publish_add_model_dialog_event();
    fn publish_clear_model_dialog_event();
    fn publish_set_language_event(value: u32);
    fn publish_query_open_single_file_dialog_event();
    fn publish_query_open_multiple_files_dialog_event();
    fn publish_query_save_file_dialog_event();
    fn publish_update_progress_event(value: u32, total: u32, typ: u32, text: String);
    fn publish_start_progress_event(title: String, text: String, total: u32);
    fn publish_stop_progress_event();
    fn publish_setup_progress_event();
    fn publish_set_editing_mode_event();
    fn publish_complete_exporting_image_configuration_event();
    fn publish_complete_exporting_video_configuration_event();
    fn publish_can_copy_event(value: bool);
    fn publish_can_paste_event(value: bool);
    fn publish_set_window_device_pixel_ratio_event(value: u32);
    fn publish_set_viewport_device_pixel_ration_event(value: u32);
    fn publish_disable_cursor_event();
    fn publish_enable_cursor_event();
    fn publish_quit_application_event();
    fn publish_error_event(error: impl Exception);
}