pub type NanoemModel = nanoem::model::Model;
pub type NanoemVertex = nanoem::model::ModelVertex;
pub type NanoemBone = nanoem::model::ModelBone;
pub type NanoemMaterial = nanoem::model::ModelMaterial;
pub type NanoemMorph = nanoem::model::ModelMorph;
pub type NanoemConstraint = nanoem::model::ModelConstraint;
pub type NanoemConstraintJoint = nanoem::model::ModelConstraintJoint;
pub type NanoemLabel = nanoem::model::ModelLabel;
pub type NanoemRigidBody = nanoem::model::ModelRigidBody;
pub type NanoemJoint = nanoem::model::ModelJoint;
pub type NanoemSoftBody = nanoem::model::ModelSoftBody;
pub type NanoemTexture = nanoem::model::ModelTexture;
pub type VertexIndex = usize;
pub type BoneIndex = usize;
pub type MaterialIndex = usize;
pub type MorphIndex = usize;
pub type ConstraintIndex = usize;
pub type LabelIndex = usize;
pub type RigidBodyIndex = usize;
pub type JointIndex = usize;
pub type SoftBodyIndex = usize;

pub mod bone;
pub mod constraint;
pub mod model;
pub mod morph;
pub mod rigid_body;
pub mod vertex;
pub mod material;
pub mod joint;

pub use bone::Bone;
pub use model::Model;
pub use morph::Morph;
pub use rigid_body::RigidBody;
pub use vertex::{Vertex, VertexUnit};
pub use material::Material;
pub use joint::Joint;
