name: CI

on:
  push:
    branches: [ "master" ]
    tags: [v0.*]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build-wasm:
    runs-on: ubuntu-latest

    env:
      RUSTFLAGS: --cfg=web_sys_unstable_apis

    steps:
    - uses: actions/checkout@v3

    - name: Install wasm-pack
      run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh
      
    - name: caching
      uses: Swatinem/rust-cache@v2

    - name: Build
      run: wasm-pack build mdanceio-wasm --out-dir ../target/pkg && python3 scripts/update_wasm_pkg.py target/pkg

    - name: Build with WebGL support
      run: wasm-pack build mdanceio-wasm --out-dir ../target/pkg-webgl --scope webgl-supports -- --features webgl && python3 scripts/update_wasm_pkg.py target/pkg-webgl
    
    - uses: actions/upload-artifact@v3
      with:
        name: npm-package
        path: target/pkg/
    
    - uses: actions/upload-artifact@v3
      with:
        name: npm-package-webgl
        path: target/pkg-webgl/
  
  build-example:
    strategy: 
      fail-fast: false
      matrix: 
        include:
          # Windows
          - name: Windows x86_64
            os: windows-latest
            target: x86_64-pc-windows-msvc
            bin-name: winit_app.exe
            artifact-name: winit_app_windows_x86_64
          # Linux
          - name: Linux x86_64
            os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            bin-name: winit_app
            artifact-name: winit_app_ubuntu_x86_64
          # MacOS
          - name: MacOS x86_64
            os: macos-latest
            target: x86_64-apple-darwin
            bin-name: winit_app
            artifact-name: winit_app_macos_x86_64
    
    name: Build Winit Demo ${{ matrix.name }}
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v3
      
    - name: caching
      uses: Swatinem/rust-cache@v2
      with:
        key: ${{ matrix.target }}-b

    - name: Build Example
      run: cargo build --package mdanceio --example winit_app --release
    
    - uses: actions/upload-artifact@v3
      with:
        name: ${{ matrix.artifact-name }}
        path: target/release/examples/${{ matrix.bin-name }}

  build-web-demo:

    runs-on: ubuntu-latest

    env:
      RUSTFLAGS: --cfg=web_sys_unstable_apis

    steps:
    - uses: actions/checkout@v3

    - name: Install wasm-pack
      run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh
      
    - name: caching
      uses: Swatinem/rust-cache@v2

    - name: Build Wasm Pack
      run: wasm-pack build mdanceio-wasm --out-dir ../target/pkg && python3 scripts/update_wasm_pkg.py target/pkg

    - name: Build Wasm Pack with WebGL support
      run: wasm-pack build mdanceio-wasm --out-dir ../target/pkg-webgl --scope webgl-supports -- --features webgl && python3 scripts/update_wasm_pkg.py target/pkg-webgl

    - name: Use Node.js 16.x
      uses: actions/setup-node@v3
      with:
        node-version: 16.x
        cache: 'npm'
        cache-dependency-path: mdance-demo/package-lock.json

    - name: Install Dependencies
      working-directory: ./mdance-demo
      run: npm install

    - name: Build
      working-directory: ./mdance-demo
      run: npm run build
    
    - uses: actions/upload-artifact@v3
      with:
        name: mdanceio-web-demo
        path: mdance-demo/build/

  build-aar:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      
    - name: caching
      uses: Swatinem/rust-cache@v2
    
    - name: Update build target
      run: rustup target add aarch64-linux-android armv7-linux-androideabi x86_64-linux-android i686-linux-android
    
    - name: Install cargo Binary Tools
      run: cargo install cargo-ndk

    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        server-id: github
        settings-path: ${{ github.workspace }}

    - name: Install NDK
      if: steps.ndk-cache.outputs.cache-hit != 'true'
      run: echo "y" | sudo /usr/local/lib/android/sdk/tools/bin/sdkmanager --install "ndk;26.1.10909125"

    - name: Build with Gradle
      uses: gradle/gradle-build-action@v2
      with:
        arguments: :mdanceio-ar:build
    
    - name: Upload build aar
      uses: actions/upload-artifact@v3
      with:
        name: build-aar
        path: mdanceio-android/android/build/outputs/aar
